name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  create-cli-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11' 
    
      - name: Install dependencies and Build Windows CLI
        shell: pwsh
        run: |
          $env:PATH += ";C:\ProgramData\chocolatey\lib\python\tools"
          pip install pyinstaller
          pyinstaller res_cli.py --onefile --name res-cli-windows
          7z a ./cli-windows.zip ./dist/
    
      - name: Upload CLI Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cli-windows
          path: ./cli-windows.zip

  create-cli-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11' 

      - name: Create CLI
        run: |
          pip install pyinstaller
          pyinstaller res_cli.py --onefile --name res-cli-linux
          zip -r cli-linux.zip dist/res-cli-linux

      - name: Upload CLI Linux Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cli-linux
          path: ./cli-linux.zip

  create-cli-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11' 

      - name: Build Mac CLI
        run: |
          brew install python@3.11
          pip install pyinstaller
          pyinstaller res_cli.py --onefile --name res-cli-mac
          zip -r cli-mac.zip dist/res-cli-mac

      - name: Upload CLI Mac Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cli-mac
          path: ./cli-mac.zip