name: CI/CD

on:
  push:
    branches:
      - main

jobs:
#   unit-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install poetry
#           poetry install

#       - name: Run tests
#         run: poetry run pytest

#   format:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install poetry
#           poetry install

#       - name: Format Checking
#         run: poetry run make format-check

  create-cli-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Windows CLI
        shell: pwsh
        run: |
          choco install pyenv-win -y --force
          refreshenv
          pyenv install 3.11.0b4
          pyenv global 3.11.0b4
          pyenv shell 3.11.0b4
          curl -sSL https://install.python-poetry.org | python3 -
          "$HOME/.local/bin/poetry" install
          "$HOME/.local/bin/poetry" run pyinstaller res_cli.py --onefile --name res-cli-windows
          7z a ./cli-windows.zip ./dist/

      - name: Upload CLI Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cli-windows
          path: ./cli-windows.zip

  create-cli-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
        working-directory: ${{ github.workspace }}

      - name: Create CLI
        run: |
          poetry run pyinstaller res_cli.py --onefile --name res-cli-linux
          zip -r cli-linux.zip dist/res-cli-linux
        working-directory: ${{ github.workspace }}

      - name: Upload CLI Linux Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cli-linux
          path: ./cli-linux.zip

  create-cli-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Mac CLI
        run: |
          brew install python@3.11
          curl -sSL https://install.python-poetry.org | python3.11 -
          /Users/runner/.local/bin/poetry install
          /Users/runner/.local/bin/poetry run pyinstaller res_cli.py --onefile --name res-cli-mac
          zip -r cli-mac.zip dist/res-cli-mac

      - name: Upload CLI Mac Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cli-mac
          path: ./cli-mac.zip
